{% set name = "fps-notebook" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_notebook-{{ version }}.tar.gz
  sha256: 784ea662e126da6f5bc287e5dfa5f981b6a560dcf44455f01942d2dfc3a49f4f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.7.0,<1
    - notebook >=7.1.2,<8.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_notebook

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/notebook
  summary: An FPS plugin for the Notebook API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/notebook
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
