{% set name = "fps-notebook" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_notebook-{{ version }}.tar.gz
  sha256: 104ac293a7f2bc728cb9431b625ec98d2db72e3fa8c94806a02d180aeb49f0da

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - jupyverse-api >=0.1.4,<1
    - notebook >=7.1.2,<8.0.0

test:
  imports:
    - fps_notebook

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/notebook
  summary: An FPS plugin for the Notebook API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/notebook
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
