{% set name = "fps-notebook" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_notebook-{{ version }}.tar.gz
  sha256: 1c41153d82f0cb43d8bbb72ee4d517b97875b99a0ae3bf1f2521a8f4552e4ad7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.9.0,<0.10.0
    - notebook-frontend >=7.4.2,<8.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_notebook

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/notebook
  summary: An FPS plugin for the Notebook API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/notebook
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
