{% set name = "fps-notebook" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_notebook-{{ version }}.tar.gz
  sha256: 2c2e5da0c94624a616889781c3f63933a4d659c80bc9afc8fabbc2e927a033b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.13.0,<0.14.0
    - notebook-frontend >=7.4.2,<8.0.0

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fps_notebook

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/notebook
  summary: An FPS plugin for the Notebook API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/notebook
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
